version: '3.8'

services:
  benefit-eligibility:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubi-eligibility-sdk
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data: 